# Generated by Django 3.1.1 on 2021-02-26 15:56

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210226_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='profile/default_profile.jpg', upload_to=users.models.user_directory_path),
        ),
    ]
