# Generated by Django 3.1.1 on 2021-03-02 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210228_1743'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
