# Generated by Django 3.1.1 on 2021-02-22 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gallery.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('img_width', models.PositiveIntegerField()),
                ('img_height', models.PositiveIntegerField()),
                ('image', models.ImageField(height_field='img_height', upload_to=gallery.models.user_directory_path, verbose_name='Photo', width_field='img_width')),
                ('description', models.TextField(blank=True, max_length=300, verbose_name='description')),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
