# Generated by Django 3.1.1 on 2021-02-23 14:58

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20210222_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='img_height',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='img_width',
        ),
        migrations.AlterField(
            model_name='photo',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=gallery.models.user_directory_path, verbose_name='Photo'),
        ),
    ]
