# Generated by Django 3.1.1 on 2021-02-23 14:59

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20210223_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=gallery.models.user_directory_path, verbose_name='photo'),
        ),
    ]
