# Generated by Django 3.1.1 on 2021-02-22 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20210222_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='photographer',
            new_name='user',
        ),
    ]
