# Generated by Django 3.1.1 on 2021-02-25 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20210223_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='photographer',
            new_name='user',
        ),
    ]
