# Generated by Django 3.1.1 on 2021-03-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_auto_20210304_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.CharField(max_length=300, verbose_name='comment_text'),
        ),
    ]
