# Generated by Django 3.1.1 on 2021-03-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_auto_20210315_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='useralbum',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
