# Generated by Django 3.1.1 on 2021-03-15 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_useralbum_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumphoto',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='gallery.photo'),
        ),
    ]
