# Generated by Django 3.1.1 on 2021-03-15 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0015_auto_20210315_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumphoto',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.photo'),
        ),
    ]
