# Generated by Django 3.1.1 on 2021-03-18 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0016_auto_20210315_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useralbum',
            old_name='photos',
            new_name='album_photos',
        ),
    ]
