# Generated by Django 3.1.1 on 2021-03-18 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0017_auto_20210318_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useralbum',
            name='album_photos',
        ),
        migrations.RemoveField(
            model_name='useralbum',
            name='user',
        ),
        migrations.DeleteModel(
            name='AlbumPhoto',
        ),
        migrations.DeleteModel(
            name='UserAlbum',
        ),
    ]
