# Generated by Django 3.1.1 on 2021-05-27 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0018_auto_20210318_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='likes',
        ),
    ]
