# Generated by Django 3.1.1 on 2021-02-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('nickname', models.CharField(max_length=20, unique=True, verbose_name='닉네임')),
                ('profile_image', models.ImageField(upload_to='', verbose_name='프로필사진')),
                ('password', models.CharField(max_length=128, verbose_name='비밀번호')),
                ('introduce', models.TextField(max_length=500, verbose_name='소개')),
                ('registered_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '계정',
                'verbose_name_plural': '계정',
                'db_table': 'account',
            },
        ),
    ]
