# Generated by Django 3.1.1 on 2021-02-15 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='account',
        ),
    ]
