# Generated by Django 3.1.1 on 2021-05-27 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useralbum',
            options={'ordering': ['-date_created']},
        ),
    ]
